language: node_js
node_js: lts/*
sudo: false

branches:
  only:
    - hexo_source

cache:
  directories:
    - node_modules
 
before_install:
  - export TZ='America/New_York'


install:
  - npm install -g hexo-cli # 安装 Hexo 
  - npm install # 安装 Hexo 依赖

script:
  - hexo clean
  - hexo generate

after_script:
  - git config --local user.name "travis-ci"
  - git config --local user.email "deploy@travis-ci.org"
  - sed -i'' "s~git@github.com:~https://${GITHUB_REPO_TOKEN}@github.com/~" _config.yml
  - hexo deploy
